### ISSUE TITLE
Revert gradle.properties if any builds in subproject fails.

### ISSUE THREAD

**Issue by kavink** [akhikhl/multiproject-git-gradle#14]
Revert changes in "gradle.properties" files in case of errors (for example, build errors) and also delete any tags created.
e.g. If project 1 was released (i.e. build succeeded and deployed to maven/artifactory), but project 2 failed. Then project 1 should be good but project 2 changes should be reverted.

if possible all releases should be tried , if any fails then last known versions should be used downstream.

There should be a flag for failOnAnyFailure or continue with all releases and use last known version for repos which failed.

By default flag failOnAnyFailure should be true, Always fail if any failures.

Also git push and upload archives should happen as last step of release. i.e. if uploadArchives/artifactory publish fails, git changes should be reverted.

**Comment by akhikhl** [comment]
Currently implemented (not yet documented) sequence of internal release tasks looks like this:

```
releaseChecks
releaseCollectVersions
releaseResolveVersions
releasePrepareReleaseVersions
releaseCheckSnapshotDependencies
releaseBuild
releaseCreateReleaseTags
releasePrepareNewVersions
releaseCommitNewVersions
```

Each task iterates all involved git repositories and does not proceed to the next task until all git repositories are successfully handled. For example releaseBuild builds code in all repositories and only then proceeds to releaseCreateReleaseTags when all repositories are successfully built.

Tasks `[releaseChecks..releaseBuild]` do not modify git repositories. They modify "gradle.properties" files at most.

Git modifications are performed only by tasks releaseCreateReleaseTags and releaseCommitNewVersions.

My suggestion:
- ARF should only revert "gradle.properties" files in case of build errors, because these are only the changed files until all builds are successfully finished.
- ARF should not try to handle errors with git commit and git push, since those are very unlikely to happen. Consider: releaseChecks actually checks that all git repositories do not have uncommitted changes and are in sync with upstream (not ahead and not behind it).

My motivation is the following: lets implement a system that keeps complexity comparably low and that covers 99% of cases. Your opinion?

**Comment by kavink** [comment]
Agree with your suggestions! keeping system simple and workable with known process/workaround on what to do if it fails. is fine too.

**Comment by akhikhl** [comment]
Resolved in version 1.0.18.

**Comment by kavink** [comment]
Thanks! will test it .

**Comment by kavink** [comment]
This works as expected, if we can do a gitRevert command also would be great so its as good as a new clone.

**Comment by kavink** [comment]
Closing as its good enough, As i do nuke for every run.
